name: flutter_clean_architecture_01
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  flutter_bloc: ^9.1.1
  hive_flutter: ^1.1.0
  equatable: ^2.0.8
  get_it: ^9.2.0
  dartz: ^0.10.1
  hive: ^2.2.3
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
